### ISSUE TITLE
List of todo items before the alpha release

### ISSUE THREAD

**Issue by ravisvi** [sanity/tahrir#50]
Many things are to be done before the alpha release but I'm hoping none of them require major changes to the existing codebase.
- [ ] Ability to remove a useridentity. 
  Currently new identities for a user can be added via the registerWindow, but no way of removing an identity.
- [ ] Follow a user. (Unfollow also.) 
  Should be made possible by clicking on the author of the broadcast message and selecting to follow. (Methods are already available, UI has to be created.)
  Also, when a user is unfollowed, the user must be removed from contactBook. 
- [ ] When a broadcastMessage is boosted, rather than creating a redundant entry on the table (as happening now), the boosted broadcastMessage must shift up in the table. This can be implemented in 2 ways. Either the boosted broadcastMessage is pushed on top, or the display of broadcastmessages are ordered on priority, i.e most recent or boosted broadcastMessage has higher priority.
